<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Gift Card Account by Amasty (System)
 */
/**
 * @var $block Amasty\GiftCardAccount\Block\Adminhtml\Sales\Order\Create\GiftCard;
 * @var $escaper Magento\Framework\Escaper
 */
?>
<?php if ($block->isGiftCardEnable()): ?>
<div class="admin__field field-apply-coupon-code"
     data-mage-init='{"Amasty_GiftCardAccount/js/order": {}}'>
    <label class="admin__field-label">
        <span><?= $escaper->escapeHtml(__('Gift Cards')) ?></span></label>
    <div class="admin__field-control">
        <input type="text" class="admin__control-text" id="amgiftcard_code" value="" name="amgiftcard_code"/>
        <button type="button" value="" class="action-default" data-amgiftcard="apply">
            <span><?= $escaper->escapeHtml(__('Apply')) ?></span>
        </button>
        <?php foreach ($block->getGiftCards() as $card): ?>
            <p class="added-coupon-code">
                <span><?=  $escaper->escapeHtml($card) ?></span>
                <a href="#"
                   title="<?= $escaper->escapeHtml(__('Remove Gift Cards Code')) ?>"
                   class="action-remove"
                   data-amgiftcard="remove"
                   data-amgiftcard-remove-code="<?= $escaper->escapeJs($card) ?>">
                    <span><?= $escaper->escapeHtml(__('Remove')) ?></span>
                </a>
            </p>
        <?php endforeach; ?>
    </div>
</div>
<?php endif; ?>
