<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate

/** @var $block \Magento\Sales\Block\Order\Email\Items\DefaultItems */

/** @var $_item \Magento\Sales\Model\Order\Item */
/** @var \Magento\Framework\Escaper $escaper */
$_item = $block->getItem();
$_order = $_item->getOrder();
$_store = $_order->getStore();

    $productId = $_item->getProductId();
    $objectManagerHere = \Magento\Framework\App\ObjectManager::getInstance();
    $product = $objectManagerHere->get('Magento\Catalog\Model\Product')->load($productId);
    $productImage = $this->helper('Magento\Catalog\Helper\Image')->init($product, 'category_page_list', array('height' => '65' , 'width'=> '65'))->getUrl();

?>
<tr>
    <td class="item-info<?= ($block->getItemOptions() ? ' has-extra' : '') ?>">
        <img height="100" width="100" src="<?= $productImage ?>" alt="<?= __('Product Image');?>" />
    </td>
    <td class="item-info<?= ($block->getItemOptions() ? ' has-extra' : '') ?>">
        <a href="<?= $escaper->escapeHtml($_item->getProduct()->getProductUrl()) ?>">
            <p class="product-name"><?= $escaper->escapeHtml($_item->getName()) ?></p>
        </a>
        <p class="sku"><?= $escaper->escapeHtml(__('SKU')) ?>: <?= $escaper->escapeHtml($block->getSku($_item)) ?></p>
        <?php

        $product = $_item->getProduct();
        /** @var \Magento\Sales\Model\Order\Item[] $children */
        if ($children = $_item->getChildrenItems()) {
            foreach ($children as $child) {
                $product = $child->getProduct();
            }
        }
        /** @var \Crimson\ProductBackorderNotification\Block\BackorderInformation $backOrderInformation */
        $backOrderInformation = $block->getChildBlock('backorder_information');
        if ($backOrderInformation) {
            $backOrderInformation->setProduct($product);
            echo $backOrderInformation->toHtml();
        }

        ?>

		 <?php if ($block->getItemOptions()) : ?>
            <dl class="item-options dl-horizontal">
            <?php foreach ($block->getItemOptions() as $option) : ?>
                <dt><strong><em><?= $escaper->escapeHtml($option['label']) ?></em></strong></dt>
                <dd>
                    <?= /* @noEscape */  htmlspecialchars_decode($escaper->escapeHtml($option['value'])) ?>
                </dd>
            <?php endforeach; ?>
            </dl>
        <?php endif; ?>
        <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addInfoBlock) :?>
            <?= $addInfoBlock->setItem($_item)->toHtml() ?>
        <?php endif; ?>
        <?= $escaper->escapeHtml($_item->getDescription()) ?>
    </td>
	<td>&nbsp;</td>
    <td class="item-qty"><?= (float) $_item->getQtyOrdered() ?></td>
    <td class="item-price">
        <?= /* @noEscape */ $block->getItemPrice($_item) ?>
    </td>
</tr>
<?php if ($_item->getGiftMessageId()
    && $_giftMessage = $this->helper(\Magento\GiftMessage\Helper\Message::class)
        ->getGiftMessage($_item->getGiftMessageId())
) : ?>
    <tr>
    <td colspan="3" class="item-extra">
        <table class="message-gift">
            <tr>
                <td>
                    <h3><?= $escaper->escapeHtml(__('Gift Message')) ?></h3>
                    <strong><?= $escaper->escapeHtml(__('From:')) ?></strong> <?= $escaper->escapeHtml($_giftMessage->getSender()) ?>
                    <br /><strong><?= $escaper->escapeHtml(__('To:')) ?></strong> <?= $escaper->escapeHtml($_giftMessage->getRecipient()) ?>
                    <br /><strong><?= $escaper->escapeHtml(__('Message:')) ?></strong>
                    <br /><?= $escaper->escapeHtml($_giftMessage->getMessage()) ?>
                </td>
            </tr>
        </table>
    </td>
</tr>
<?php endif; ?>
