<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Store Credit & Refund for Magento 2
 */
/**
 * @var \Amasty\StoreCredit\Block\Adminhtml\Total $block
 */
 /** @var Magento\Framework\Escaper $escaper */
?>
<?php if ($block->getStoreCredit()): ?>
    <tr>
        <td class="label"><?= $escaper->escapeHtml(__('Store Credit')); ?></td>
        <td>
            <?=  /* @noEscape */ $block->getFormatStoreCredit(); ?>
        </td>
    </tr>
<?php endif; ?>
