<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Multishipping checkout billing information
 *
 * @var $block \Magento\Multishipping\Block\Checkout\Billing
 */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>
<?php
$blockObj= $block->getLayout()->createBlock('Credova\Financial\Block\Aslowas');
$credovatitlte = $blockObj->getCredovaTitle();
$min_amount = $blockObj->getCredovaMinimumAmount();
$max_amount = $blockObj->getCredovaMaximumAmount();
$env = $blockObj->getCredovaEnvironment();
$AslowasOnCart = $blockObj->getCredovaAslowasOnCart();
$credova_api_username = $blockObj->getApiUsername();
$popup_type = $blockObj->getCredovaPopupType();
$hide_brand = $blockObj->getCredovaHideBrand();
$white_logo = $blockObj->getCredovaWhiteLogoEnable();
 $credovaActive = $blockObj->getCredovaActive();
$quote = $blockObj->Summarydata()->getQuote();
 $finall_price = $quote->getGrandTotal();

 $monthlyp = $blockObj->getMinALA();

if ($env == 0) {
    $env = 'Production';
} else {
    $env = 'Sandbox';
}

?>
<div id="checkout-loader" data-role="checkout-loader" class="loading-mask" data-mage-init='{"billingLoader": {}}'>
    <div class="loader">
        <img src="<?= $block->escapeUrl($block->getViewFileUrl('images/loader-1.gif')); ?>"
             alt="<?= $block->escapeHtmlAttr(__('Loading...')); ?>"
             style="position: absolute;">
    </div>
</div>
<?php
$scriptString = <<<script
    window.checkoutConfig = {$block->getCheckoutData()->getSerializedCheckoutConfigs()};
    window.isCustomerLoggedIn = window.checkoutConfig.isCustomerLoggedIn;
    window.customerData = window.checkoutConfig.customerData;
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false); ?>
<div id="checkout" data-bind="scope:'checkoutMessages'">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "#checkout": {
                "Magento_Ui/js/core/app": {
                   "components": {
                        "checkoutMessages": {
                            "component": "Magento_Ui/js/view/messages",
                            "displayArea": "messages"
                        }
                    }
                }
            }
        }
    </script>
</div>
<form action="<?= $block->escapeUrl($block->getPostActionUrl()); ?>"
      method="post"
      id="multishipping-billing-form"
      class="form multicheckout billing">
    <div class="block block-billing">
        <div class="block-content">
            <div class="box box-billing-address">
                <strong class="box-title">
                    <span><?= $block->escapeHtml(__('Billing Address')); ?></span>
                    <a href="<?= $block->escapeUrl($block->getSelectAddressUrl()); ?>" class="action">
                        <span><?= $block->escapeHtml(__('Change')); ?></span>
                    </a>
                </strong>
                <div class="box-content">
                    <address>
                        <?= /* @noEscape */ $block->getCheckoutData()->getAddressHtml($block->getAddress()); ?>
                    </address>
                </div>
            </div>
            <div class="box box-billing-method">
                <fieldset class="fieldset">
                    <legend class="legend box-title">
                        <span><?= $block->escapeHtml(__('Payment Method')); ?></span>
                    </legend><br>
                    <div class="box-content">
                        <?= $block->getChildHtml('payment_methods_before') ?>
                        <?php /* Payment methods forms list */ ?>
                        <dl class="checkout-payment-method" id="payment-methods">
                            <?php
                            $methods = $block->getMethods();
                            $methodsCount = count($methods);
                            $methodsForms = $block->hasFormTemplates() ? $block->getFormTemplates(): [];

                            foreach ($methods as $_method):
                                    $code = $_method->getCode();
                                    $checked = $block->getSelectedMethodCode() === $code;

                                if (isset($methodsForms[$code])) {
                                    $block->setMethodFormTemplate($code, $methodsForms[$code]);
                                }
                                ?>
                                <div data-bind="scope: 'payment_method_<?= $block->escapeHtml($code);?>'">
                                    <dt class="item-title">
                                        <?php if ($methodsCount > 1): ?>
                                            <input type="radio"
                                                   id="p_method_<?= $block->escapeHtml($code); ?>"
                                                   value="<?= $block->escapeHtmlAttr($code); ?>"
                                                   name="payment[method]"
                                                   title="<?= $block->escapeHtmlAttr($_method->getTitle()) ?>"
                                                   data-bind="
                                                       value: getCode(),
                                                       checked: isChecked,
                                                       click: selectPaymentMethod,
                                                       visible: isRadioButtonVisible()"
                                                <?php if ($checked): ?>
                                                    checked="checked"
                                                <?php endif; ?>
                                                   class="radio"/>
                                        <?php else: ?>
                                            <input type="radio"
                                                   id="p_method_<?= $block->escapeHtml($code); ?>"
                                                   value="<?= $block->escapeHtmlAttr($code); ?>"
                                                   name="payment[method]"
                                                   data-bind="
                                                       value: getCode(),
                                                       afterRender: selectPaymentMethod"
                                                   checked="checked"
                                                   class="radio solo method" />
                                        <?php endif; ?>
                                        <?php if ($credovaActive == 1 && $code =="credovafinancial") { ?>
                                            <?php if ($finall_price > $min_amount && $finall_price < $max_amount && $AslowasOnCart == 1) {
                                                ?>
<?php
$styleString = <<<style
                                                    #credova_white .crdv-text {
                                                        color: #FFF7EE !important;
                                                        background: transparent !important;
                                                    }
style;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('style', [], $styleString, false); ?>
                                                <p class="credova-button" data-amount="<?php echo $finall_price; ?>" data-type="text" <?php if ($white_logo == 1) { ?>id = "credova_white"<?php } ?>></p>
<?php
$scriptString = <<<script
                                                    CRDV.plugin.config({ environment: CRDV.Environment.{$env}, store: "{$credova_api_username}" });
                                                    CRDV.plugin.inject("credova-button");
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false); ?>
                                                <?php
                                            } ?>
                                       <?php }?>
                                        
                                        <label <?php if ($code =="credovafinancial") { echo
                                            "style='display:none;'";
                                               } ?> for="p_method_<?= $block->escapeHtml($code); ?>">
                                            <?= $block->escapeHtml($_method->getTitle()) ?>
                                        </label>

                                    </dt>
                                    <?php if ($html = $block->getChildHtml('payment.method.' . $code)): ?>
                                        <dd class="item-content <?= $checked ? '' : 'no-display'; ?>">
                                            <?= /* @noEscape */ $html; ?>
                                        </dd>
                                    <?php endif; ?>
                                </div>
                            <?php endforeach; ?>
                        </dl>
                        <?= $block->getChildHtml('payment_methods_after') ?>
                        <?= $block->getChildHtml('checkout_billing_items') ?>
                    </div>
                </fieldset>
            </div>
        </div>
    </div>
    <div class="actions-toolbar">
        <div class="primary" id="parent-payment-continue">
            <button id="payment-continue"
                    type="button"
                    class="action primary continue">
                <span><?= $block->escapeHtml(__('Go to Review Your Order')); ?></span>
            </button>
        </div>
        <div class="secondary">
            <a href="<?= $block->escapeUrl($block->getBackUrl()); ?>" class="action back">
                <span><?= $block->escapeHtml(__('Back to Shipping Information')); ?></span>
            </a>
        </div>
    </div>
</form>
<?php
$baseGrandTotal = (float)$block->getQuoteBaseGrandTotal();
$scriptString = <<<script
    require(['jquery', 'mage/mage'], function(jQuery) {
        var addtocartForm = jQuery('#multishipping-billing-form');

        addtocartForm.mage('payment', {
            checkoutPrice: {$baseGrandTotal}
        });

        addtocartForm.mage('validation', {
            errorPlacement: function(error, element) {
                if (element.attr('data-validate') && element.attr('data-validate').indexOf('validate-cc-ukss') >= 0) {
                    element.parents('form').find('[data-validation-msg="validate-cc-ukss"]').html(error);
                } else {
                    element.after(error);
                }
            }
        });
    });
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false); ?>

<?php
$street = json_encode($block->getAddress()->getStreet());
$scriptString = <<<script
    //<![CDATA[
    require(
        [
            'Magento_Checkout/js/model/quote',
            'jquery',
            'domReady!'
        ], function(quote, $) {
            quote.billingAddress({
                    city: '{$block->getAddress()->getCity()}',
                    company: '{$block->getAddress()->getCompany()}',
                    countryId: '{$block->getAddress()->getCountryId()}',
                    customerAddressId: '{$block->getAddress()->getCustomerAddressId()}',
                    customerId: '{$block->getAddress()->getCustomerId()}',
                    fax: '{$block->getAddress()->getFax()}',
                    firstname: '{$block->getAddress()->getFirstname()}',
                    lastname: '{$block->getAddress()->getLastname()}',
                    postcode: '{$block->getAddress()->getPostcode()}',
                    regionId: '{$block->getAddress()->getRegionId()}',
                    regionCode: '{$block->getAddress()->getRegionCode()}',
                    region: '{$block->getAddress()->getRegion()}',
                    street: {$street},
                    telephone: '{$block->getAddress()->getTelephone()}'
            });
        });
    //]]>
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false); ?>

