<?php
/**
* Copyright © 2019 Codazon. All rights reserved.
* See COPYING.txt for license details.
*/
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>
<?php
$scriptString = <<<script
require(['jquery/jquery.cookie'], function() {
    if (jQuery.cookie('mage-messages')) {
        require(['Magento_Customer/js/customer-data'], function(customerData) {
            customerData.reload(['cart'], true);
        });
    }
});
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false); ?>
