<?php
/**
 * Copyright © 2017 Codazon, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
 ?>
<?php
$helper = $this->helper('Codazon\ThemeLayoutPro\Helper\Data');
$layout = $this->getLayout();
echo $helper->htmlFilter($helper->getConfig('themelayoutpro/general/head_script'));

$themeVars = json_encode($helper->getThemeGlobalVariables());
$scriptString = <<<script
var codazon = {$themeVars}
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', ['id' => 'codazon-global-config'], $scriptString, false); ?>

<?= $helper->getCssScript($layout) ?>

<?php if (false) : /* $helper->isDeveloperMode() */ ?>
<?php
$lessFileSet = json_encode($helper->getLessFilesSet());
$scriptString = <<<script
less.options.relativeUrls = false;
less.options.rootpath = '{$helper->getMediaUrl()}';
var lessFileSet = {$lessFileSet};
var lessElement;
for(var lessIndex in lessFileSet) {
    lessElement = document.createElement('link');
    lessElement.rel = "stylesheet/less";
    lessElement.href = lessFileSet[lessIndex];
    less.sheets.push(lessElement);
}
less.refresh();
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false); ?>
<?php endif ?>
<?php
if ($helper->isMagento23x()) {
    $cssFiles = [
        $block->getViewFileUrl('mage/calendar.css'),
        $block->getViewFileUrl('css/animate/animate.css')
    ];
} else {
    $cssFiles = [
        $block->getViewFileUrl('mage/calendar.css'),
        $block->getViewFileUrl('Magento_Swatches::css/swatches.css'),
        $block->getViewFileUrl('css/animate/animate.css'),
    ];
}
$version = str_replace('-dev', '', $helper->getMagentoVersion());
?>
<?php if (version_compare($version, '2.3.2', '<=')) : ?>
<?php
$scriptString = <<<script
require.config({
    map: {
        '*': {
            'jquery-ui-modules/widget': 'jquery/ui',
            'jquery-ui-modules/autocomplete': 'jquery/ui',
            'jquery-ui-modules/slider': 'jquery/ui',
        }
    }
});
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false); ?>
<?php endif ?>
<?php
$cssFilesEnc = json_encode($cssFiles);
$scriptString = <<<script
var windowLoaded = false;
window.addEventListener('load', function() {
    windowLoaded = true;
}, true);
require(['jquery'], function($) {
    require(['Codazon_ThemeLayoutPro/js/material-theme']);
    function loadCSSLinks() {
        require(['jquery/jquery.cookie'], function() {
            var styles = {$cssFilesEnc}, cookieName = 'css_first_load';
            if ($.cookie(cookieName)) { var t = 200; } else {
                var date = new Date(), t = 5000; date.setTime(date.getTime() + (8640000000)); $.cookie(cookieName, '1', {path: '/', expires: date});
            }
            setTimeout(function() {
                $.each(styles, function(i, styleFile) { $('head').prepend('<'+'link rel="stylesheet" type="text/css" media="all" href="' + styleFile +'" >'); });
                $('head').prepend('<'+'link rel="stylesheet" type="text/css" media="print" href="{$block->getViewFileUrl('css/print.css')}" >');
            }, t);
        });
    }
    windowLoaded ? loadCSSLinks() : $(window).on('load', loadCSSLinks);
    var updateTimeout = false;
    $('body').on('contentUpdated', function () {
        if (updateTimeout) clearTimeout(updateTimeout);
        require(['mage/apply/main'], function(mage) {if (mage) { updateTimeout = setTimeout(function() { mage.apply(); }, 200) };});
    });
    if ($('body').hasClass('checkout-index-index')) { $(document).on('ajax:removeFromCart ajax:updateCartItemQty', function(e, productIds) { location.reload(); }); }
});
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false); ?>
<?php
$cartBlock = $layout->getBlock('minicart');
if (!$cartBlock) {
    $cartBlock = $layout->createBlock('Magento\Checkout\Block\Cart\Sidebar');
}
?>
<?php
$scriptString = <<<script
if (typeof window.checkout == 'undefined') {
    window.checkout = {$cartBlock->getSerializedConfig()};
}
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false); ?>
